esphome:
  name: smartdesklight
  friendly_name: SmartDeskLight

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "P7qBQLNfuUfGNQnKlKD6rNeGyw2JZVsd/D/J4DKRQb0="

ota:
  - platform: esphome
    password: "38e0c6cc718e9151f90641751df664e9"

wifi:
  ssid: !secret wifi_ssid_m
  password: !secret wifi_password_m 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "desklight Fallback Hotspot"
    password: "wHjqyQOLnaPa"

light:
  - platform: cwww
    name: "Livingroom Lights"
    cold_white: WLight
    warm_white: CLight
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2200 K

output:
  - platform: ledc
    id: CLight
    pin: GPIO4
    frequency: 1000 Hz
    zero_means_zero: true
    min_power: 0.0
    inverted: true
  - platform: ledc
    id: WLight
    pin: GPIO5
    frequency: 1000 Hz
    zero_means_zero: true
    inverted: true
    min_power: 0.0

captive_portal: