esphome:
  name: desklight
  friendly_name: desklight

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "desklight Fallback Hotspot"
    password: "wHjqyQOLnaPa"


i2c:
  sda: GPIO6
  scl: GPIO7
  frequency: 800kHz
  scan: true

mpr121:
  id: mpr121_component
  address: 0x5A
  touch_debounce: 1
  release_debounce: 1
  touch_threshold: 10
  release_threshold: 7

binary_sensor:
  - platform: mpr121
    id: touch_key0
    channel: 0
    name: "Touch Key 0"
    touch_threshold: 12
    release_threshold: 6

light:
  - platform: cwww
    name: "Livingroom Lights"
    cold_white: WLight
    warm_white: CLight
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2200 K
    constant_brightness: true

output:
  - platform: ledc
    id: WLight
    pin: GPIO4
    frequency: 1000 Hz
  - platform: ledc
    id: CLight
    pin: GPIO5
    frequency: 1000 Hz

captive_portal: